# yaml used instead of json due to ease and ability to comment <3

# bot requires a restart after updating config
# bot messages can be updated in the json files in this directory
# if some parts are missing, the bot will not work

bot:
    options:
        cooldown: 1440  # enter time in minutes (will only work if database is sqlite or mysql)
        queueLimit: 20  # max players in queue, dont go above something like 40 or the bot cant send a message
        testerLimit: 5  # max number of testers per region
        reloadQueue: 30 # time in seconds on how frequently you want to reload the queue, reccomended to stay above 15

    messages:           # messages to send
        noPermission: You do not have the permission to use this command.
        notTicketCatagory: Command can only be ran inside of testing channels
        resultMessageSent: Result message sent!
        error: An error as occured
        addToQueue: You have been added to queue!
        testerOpenQueue: "You have opened the queue!"
        alreadyInQueue: "You are already in the queue!"
        queueFull: "The queue is full!"
        notInQueue: "You are not in the queue!"
        leaveQueue: "You have left the queue!"
        verificationSuccess: "✅ Verified!"
        notVerified: "You must be verified to join the queue! Please use the menu in the welcome channel."
        restricted: "You are currently restricted from joining the queue."

    channels:
        results: 1497280706785579049              # results channel ID
        welcome: 0              # welcome/queue channel ID
        verification: 1497281134487408903         # verification log channel ID

    catagories:
        highTests: 1500222525198831636            # high tests category ID

    roles:
        verified: 1498359871936921780             # Queue ping role ID

    tiers:                      # Default tiers - can be overridden per gamemode
        lt5: 0
        ht5: 0
        lt4: 0
        ht4: 0
        lt3: 0
        ht3: 0
        lt2: 0
        ht2: 0
        lt1: 0
        ht1: 0
        none: 0

    highTiers:                  # tiers you want to create a seperate ticket for
        - ht1
        - lt1
        - ht2
        - lt2
        - ht3

    gamemodes:
        mace: 
            queue_channel: 1498378992405970985
            ticket_catagory: 1500223439842181210
            role_ping: 1498359871936921780
            queue_role: 1498370765362429963
            tester_role: 1500222614348628008
            verification_role: 1498370765362429963  # Role to assign when user verifies for this gamemode
            tiers:
                lt5: 1498366432885342260
                ht5: 1498366366242050191
                lt4: 1498366520181391471
                ht4: 1498366557951361094
                lt3: 1498366711185932398
                ht3: 1498366661411999744
                lt2: 1498366796456136704
                ht2: 1498366747433111674
                lt1: 1498366864710172732
                ht1: 1498366824184807637
                none: 0
        
        nethpot:
            queue_channel: 1498379072282300587
            ticket_catagory: 1500223954520903861
            role_ping: 1498359871936921780
            queue_role: 1498375923068567632
            tester_role: 1500222627791241246
            verification_role: 1498375923068567632
            tiers:
                lt5: 1498367023976288306
                ht5: 1498367016052986048
                lt4: 1498367024445915196
                ht4: 1498367024504635592
                lt3: 1498367024881995958
                ht3: 1498367024714223749
                lt2: 1498367025708273804
                ht2: 1498367025653874728
                lt1: 1498367026794860605
                ht1: 1498367026001874995
                none: 0
        
        smp:
            queue_channel: 1498379129731551344
            ticket_catagory: 1500224285300494407
            role_ping: 1498359871936921780
            queue_role: 1498375923068567632
            tester_role: 1500222627791241246
            verification_role: 1498375923068567632
            tiers:
                lt5: 1498367023976288306
                ht5: 1498367016052986048
                lt4: 1498367024445915196
                ht4: 1498367024504635592
                lt3: 1498367024881995958
                ht3: 1498367024714223749
                lt2: 1498367025708273804
                ht2: 1498367025653874728
                lt1: 1498367026794860605
                ht1: 1498367026001874995
                none: 0
        
        sword:
            queue_channel: 1498379186287546368
            ticket_catagory: 1500225605755731978
            role_ping: 1498359871936921780
            queue_role: 1498375933135159336
            tester_role: 1500222628139368658
            verification_role: 1498375933135159336
            tiers:
                lt5: 1498368425947566150
                ht5: 1498368425934983249
                lt4: 1498368425968537751
                ht4: 1498368426069069976
                lt3: 1498368426379448512
                ht3: 1498368426341826611
                lt2: 1498368427323297953
                ht2: 1498368426891284684
                lt1: 1498368427956637827
                ht1: 1498368427436277951
                none: 0
        
        uhc:
            queue_channel: 1498379317430980789
            ticket_catagory: 1500227591821463682
            role_ping: 1498359871936921780
            queue_role: 1498375933860647034
            tester_role: 1500222629024633012
            verification_role: 1498375933860647034
            tiers:
                lt5: 1498368428690636951
                ht5: 1498368428296376390
                lt4: 1498370579726598264
                ht4: 1498370582436253716
                lt3: 1498370759255396523
                ht3: 1498370753446412461
                lt2: 1498370760467550300
                ht2: 1498370759783874608
                lt1: 1498370761424113916
                ht1: 1498370760668876990
                none: 0
        
        axe:
            queue_channel: 1498379344907599893
            ticket_catagory: 1500230705857298653
            role_ping: 1498359871936921780
            queue_role: 1498375934850629753
            tester_role: 1500231015723958464
            verification_role: 1498375934850629753
            tiers:
                lt5: 1500222630710480946
                ht5: 1500222630542839908
                lt4: 1500222637496991964
                ht4: 1500231009516654763
                lt3: 1500231014545490081
                ht3: 1500231014415339730
                lt2: 1500231014876975266
                ht2: 1500231014771982477
                lt1: 1500231015610847333
                ht1: 1500231015602585732
                none: 0
        
        diamondpot:
            queue_channel: 0
            ticket_catagory: 0
            role_ping: 0
            queue_role: 0
            tester_role: 0
            verification_role: 0
            tiers:
                lt5: 0
                ht5: 0
                lt4: 0
                ht4: 0
                lt3: 0
                ht3: 0
                lt2: 0
                ht2: 0
                lt1: 0
                ht1: 0
                none: 0
        
        vanilla:
            queue_channel: 0
            ticket_catagory: 0
            role_ping: 0
            queue_role: 0
            tester_role: 0
            verification_role: 0
            tiers:
                lt5: 0
                ht5: 0
                lt4: 0
                ht4: 0
                lt3: 0
                ht3: 0
                lt2: 0
                ht2: 0
                lt1: 0
                ht1: 0
                none: 0

database:
    # options are "mysql", "sqlite", only use mysql if you know what you are doing, if you switch, data will not transfer, you will need to write your own script to transfer the data
    type: sqlite 

    mysql:      # only use this if you know what you are doing
        host: localhost
        port: 3306
        user: root
        password: root
        database: tiers # must be created before starting bot

# UwU

